apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 0
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-gitea-gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-gitea-gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.22.6
          env:
            - name: GITEA__database__DB_TYPE
              value: postgres
            - name: GITEA__database__HOST
              value: 10.100.100.87:32345
            - name: GITEA__database__NAME
              value: gitea
            - name: GITEA__database__PASSWD
              value: gitea
            - name: GITEA__database__USER
              value: gitea
            - name: USER_UID
              value: '1000'
            - name: USER_GID
              value: '1000'
          ports:
            - containerPort: 22
              name: ssh
              protocol: TCP
            - containerPort: 3000
              name: git
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          nfs:
            path: /data/gitea/data
            server: 10.100.100.13
