apiVersion: v1
kind: Service
metadata:
  name: db-nodeport
  namespace: gitea
spec:
  type: NodePort
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-gitea-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32345
