apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: g--itea-ingress
  namespace: gitea
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: g--it.int.puursam.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-service
                port:
                  number: 3000
  tls:
    - hosts:
        - git.int.puursam.be
      secretName: webserver-v1
